# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

zeebe.client:
  cloud:
    region:
    clusterId:
    clientId:
    clientSecret: